# Generated by Django 2.2.3 on 2019-07-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190716_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistitem',
            old_name='color',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='todolistitem',
            name='testing',
        ),
    ]
