# Generated by Django 2.2.3 on 2019-07-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190716_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='status',
            field=models.CharField(choices=[('True', 'Completed'), ('False', 'Incomplete')], default='False', max_length=10),
        ),
    ]
