# Generated by Django 2.2.3 on 2019-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todolistitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='priority',
            field=models.CharField(choices=[('High', 'Red'), ('Medium', 'Orange'), ('Low', 'Green')], default='green', max_length=10),
        ),
    ]
