# Generated by Django 2.2.3 on 2019-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20190716_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='green', max_length=10),
        ),
    ]
