# Generated by Django 2.2.3 on 2019-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20190716_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=10),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=10),
        ),
    ]
